# Generated by Django 3.2.9 on 2021-11-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_num', models.CharField(max_length=30)),
                ('item_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('shape', models.CharField(max_length=100)),
                ('color_front', models.CharField(max_length=30)),
                ('color_back', models.CharField(max_length=30)),
                ('bit', models.CharField(max_length=100)),
                ('prescription', models.CharField(max_length=30)),
                ('sungbun', models.CharField(max_length=100)),
                ('efcy_qesitm', models.TextField()),
                ('use_method_qesitm', models.TextField()),
                ('atpn_qesitm', models.TextField()),
                ('intrc_qesitm', models.TextField()),
                ('se_qesitm', models.TextField()),
                ('deposit_method_qesitm', models.TextField()),
            ],
        ),
    ]
