# Generated by Django 3.2.9 on 2021-11-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_infopill_precaution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopill',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
    ]
