# Generated by Django 3.2.9 on 2021-11-24 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_infopill_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopill',
            name='item_num',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='UserPill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pill_num', models.ForeignKey(db_column='pill_num', on_delete=django.db.models.deletion.CASCADE, to='api.infopill', to_field='item_num')),
                ('user_email', models.ForeignKey(db_column='user_email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
    ]
