# Generated by Django 3.2.9 on 2021-11-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_uploadfilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='files',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
