# Generated by Django 3.2.9 on 2021-11-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
